apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sregym-runner
nameSuffix: -sre-test2

resources:
  - ../../job-base

patches:
  - path: patch-job.yaml
  - path: patch-service.yaml

images:
  - name: sregym-runner
    newName: phuongbac/sregym-runner
    newTag: latest
