apiVersion: v1
kind: ServiceAccount
metadata:
  name: sregym-runner
  namespace: sregym-runner
  labels:
    app.kubernetes.io/name: sregym-runner
    app.kubernetes.io/component: runner
automountServiceAccountToken: false
